configmap:
  zookeeper:
    zkAddr: [ bitnami-zookeeper.zookeeper.svc.cluster.local:2181 ] #单机部署时，默认即可
    userName:
    password:

  mysql:
    dbMysqlAddress: [ bitnami-mysql.mysql.svc.cluster.local:3306 ] #mysql地址 目前仅支持单机，默认即可
    dbMysqlUserName: root #mysql用户名，建议修改
    dbMysqlPassword: openIM123 # mysql密码，建议修改
    dbMysqlDatabaseName: openIM_v2 #默认即可

  mongo:
    dbAddress: [ mongodb.mongodb-single.svc.cluster.local:27017 ]  #单机时为mongo地址，使用分片集群时，为mongos地址 默认即可
    dbDatabase: openIM  #mongo db 默认即可
    dbSource: admin
    dbUserName: root #mongo用户名，建议先不设置
    dbPassword: mongo123  #mongo密码，建议先不设置

  redis:
    dbAddress:  #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
      - redis-cluster-0.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
      - redis-cluster-1.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
      - redis-cluster-2.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
      - redis-cluster-3.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
      - redis-cluster-4.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
      - redis-cluster-5.redis-cluster-headless.redis-cluster.svc.cluster.local:16379
    dbUserName:     #only redis version 6.0+ need username
    dbPassWord: openIM123 #redis密码 建议修改
    enableCluster: true #如果外部redis以集群方式启动，需要打开此开关

  kafka:
    SASLUserName:
    SASLPassword:
    ws2mschat:
      addr: [ bitnami-kafka-0.bitnami-kafka-headless.kafka.svc.cluster.local:9092 ] #kafka配置，默认即可
      topic: "ws2ms_chat" #用于mongo和mysql保存消息
    msgtomongo:
      addr: [ bitnami-kafka-0.bitnami-kafka-headless.kafka.svc.cluster.local:9092 ] #kafka配置，默认即可
      topic: "msg_to_mongo"
    ms2pschat:
      addr: [ bitnami-kafka-0.bitnami-kafka-headless.kafka.svc.cluster.local:9092 ] #kafka配置，默认即可
      topic: "ms2ps_chat" #消息push
    msgtomodify:
      addr: [ bitnami-kafka-0.bitnami-kafka-headless.kafka.svc.cluster.local:9092 ] #kafka配置，默认即可
      topic: "msg_to_modify"
    consumergroupid:
      msgToTransfer: mongo
      msgToMongo: mongo_ex
      msgToMySql: mysql
      msgToPush: push
      msgToModify: modify
  minio:
    tempBucket: "openim"
    dataBucket: "openim"
    location: us-east-1
    endpoint: http://127.0.0.1:10005 #minio外网ip 这个ip是给客户端访问的
    accessKeyID: root
    secretAccessKey: openIM123
    isDistributedMod: false # 是否分布式多硬盘部署 默认docker-compose中为false，如果是多硬盘部署，需要修改为true
