# registry of image source
registry: apecloud-registry.cn-zhangjiakou.cr.aliyuncs.com

# kubeblocks-enterprise
kubeblocks-cloud:
  enable: true

kb-cloud-installer:
  enable: true

postgres-operator:
  enable: true

logto:
  enable: true

kubeblocks:
  enable: true

gemini:
  enable: true

gemini-monitor:
  enable: true

ape-local-csi-driver:
  enable: true

kubebench:
  enable: true


# addons
apecloud-mysql:
  enable: true

clickhouse:
  enable: true

elasticsearch:
  enable: true

kafka:
  enable: true

minio:
  enable: true

mongodb:
  enable: true

mysql:
  enable: true

oceanbase:
  enable: true

postgresql:
  enable: true

qdrant:
  enable: true

rabbitmq:
  enable: true

redis:
  enable: true

starrocks:
  enable: true

zookeeper:
  enable: true

damengdb:
  enable: true

kingbase:
  enable: true


# applications
ingress-nginx:
  enable: true

metallb:
  enable: true

cert-manager:
  enable: false

metrics-server:
  enable: false

spiderpool:
  enable: false
