image:
  pullPolicy: IfNotPresent
  pullSecrets:
    enabled: false
    secretName:


credentials:
  root:
    user: root
    password: supersecret
    host: "%"

tls:
  useSelfSigned: false
#  caSecretName:
#  serverCertAndPKsecretName:
#  routerCertAndPKsecretName:

#serverVersion: 8.0.30
serverInstances: 3
routerInstances: 1
baseServerId: 1000


podSpec:
  containers:
  - name: mysql
    resources:
      requests:
        memory: "2048Mi"  # adapt to your needs
        cpu: "1800m"      # adapt to your needs
      limits:
        memory: "8192Mi"  # adapt to your needs
        cpu: "3600m"      # adapt to your needs


serverConfig:
  mycnf: |
    [mysqld]
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4


#datadirVolumeClaimTemplate:
#  accessModes:
#  resources:
#    requests:
#      storage:

#initDB:
#  dump:
#    name:
#    path:
#    options:
#      includeSchemas:
#    ociObjectStorage:
#      prefix:
#      bucketName:
#      credentials:
#    persistentVolumeClaim:
#  clone:
#    donorUrl:
#    rootUser:
#    credentials:


#backupProfiles:
#- name: dump-instance-profile-pvc
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      persistentVolumeClaim:
#        claimName: backup-volume-claim-1
#- name: dump-instance-profile-oci
#  dumpInstance:
#    dumpOptions:
#      excludeSchemas: ["excludeme"]
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials
#
#- name: snapshot-profile-oci
#  snapshot:
#    storage:
#      ociObjectStorage:
#        prefix : /
#        bucketName: idbcluster_backup
#        credentials: oci-credentials

#backupSchedules:
#- name: schedule-ref
#  schedule: "*/1 * * * *"
#  deleteBackupData: false
#  backupProfileName: dump-instance-profile-oci
#  enabled: true
#- name: schedule-inline
#  schedule: "*/1 * * * *"
#  deleteBackupData: false
#  enabled: true
#  backupProfile:
#    dumpInstance:
#      dumpOptions:
#        excludeSchemas: ["excludeme"]
#      storage:
#        ociObjectStorage:
#          prefix : /
#          bucketName: idbcluster_backup
#          credentials: oci-credentials
