name: Auto build config image
on:
  issue_comment:
    types:
      - created
jobs:
  build_manifest:
    name: Auto build config image
    if: startswith(github.event.comment.body, '/imagebuild_configs')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download buildah and sealos
        run: .github/scripts/download/download.sh
      - name: Write vars
        id: autobuild
        run: |
          commentbody="${{github.event.comment.body}}"
          app=`echo "$commentbody"| awk '{print $2}'`
          version=`echo "$commentbody"| awk '{print $3}'`
          echo "::set-output name=app::$app"
          echo "::set-output name=version::$version"
      - name: Build Image
        env:
          registry: docker.io
          username: ${{ github.repository_owner }}
          repo: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY }}
          app: ${{ steps.autobuild.outputs.app }}
          version: ${{ steps.autobuild.outputs.version }}
        run: .github/scripts/configs.sh

  add-tips:
    needs:
      - build_manifest
    name: Auto add tips
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Success Commit
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ```
            image docker.io/${{ github.repository_owner }}/${{ steps.autobuild.outputs.app }}:${{ steps.autobuild.outputs.version }} build successfully!
            ```

            detail log please view [autobuild-configs](https://github.com/labring/cluster-image/actions/workflows/autobuild-configs.yml)
